Vagrant.configure("2") do |config|
  config.vm.define "ansible-role-ui.local" do |subconfig|
    subconfig.vm.box = "bento/centos-8"
    subconfig.vm.hostname = "ansible-role-ui.local"
    subconfig.vm.network :private_network, ip: "10.10.0.5"
    subconfig.ssh.insert_key = false
    subconfig.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', './devel-virtual.pub']
    subconfig.vm.provision "file", source: "./devel-virtual.pub", destination: "~/.ssh/authorized_keys"
    subconfig.vm.provision "shell", inline: <<-EOC
    sudo sed -i -e "\\#PasswordAuthentication yes# s#PasswordAuthentication yes#PasswordAuthentication no#g" /etc/ssh/sshd_config
    sudo systemctl restart sshd.service
    sudo yum install python36 -y
    echo "finished"
    EOC
  end
end
